### ISSUE TITLE
each graph algorithm should verify correctness before return

### ISSUE THREAD

**Issue by spreinhardt** [dwavesystems/dwave_networkx#71]
The DWave_NetworkX graph kernels (MIS, min vertex coloring, ...) do not confirm that the results from the underlying sampler are logically valid in the graph context; i.e., MIS does not confirm that its result is actually an independent set.  Stipulating that the underlying sampler is probabilistic and may return invalid answers, callers of DNX will expect to receive back valid answers in the graph context.

**Comment by arcondello** [comment]
One problem is that for the NP-Hard algorithms (e.g. maximum independent set) the verification function is itself NP-Hard. This means that we would be verifying some subset of the algorithm. Continuing with the example of maximum independent set, we could either check that it is a _maximal_ independent set, or just that it is an independent set. Because it is not obvious which we would check, this would violate the principle of least astonishment.

This is why we have provided explicit verification functions like [is_independent_set](https://dwave-networkx.readthedocs.io/en/latest/reference/algorithms/generated/dwave_networkx.is_independent_set.html#dwave_networkx.is_independent_set) and specified in the documentation that the solution may not be correct. This way, the user knows exactly what they have verified and if the verification is expensive, the user has actively opted in.

If there are additional verification functions you would like, please feel free to make a feature request.
