### ISSUE TITLE
need way to save created QUBO for focus by solver developers

### ISSUE THREAD

**Issue by spreinhardt** [dwavesystems/dwave_networkx#93]
DWave_NetworkX uses will often generate a graph from real-world data for solution via DNX.  The QUBO that's created inside DNX will sometimes be a high-value target for solver developers wanting to evolve their solvers to deliver better performance for real-world problems.  But currently there's no straightforward way to save the QUBO for later execution.  (In my view, it's unrealistic to expect that DNX users will ship all their data into Github so the full workflow can be recreated.  E.g., for one DNX-MIS use case, the full data is ~150GB, with complicated pre-processing scripts.)

One way to address this would be to have an argument on each algorithm signifying that the QUBO(s) should be saved in a file (or directory if multiple), possibly with the name of the file (directory) also specified.

**Comment by arcondello** [comment]
Serialization of QUBO/Ising is out of scope for dnx. 

The current serialization method in Ocean is to use `BinaryQuadraticModel.to_coo()` ([docs](https://docs.ocean.dwavesys.com/projects/dimod/en/stable/reference/generated/dimod.BinaryQuadraticModel.to_coo.html#dimod.BinaryQuadraticModel.to_coo)) or `BinaryQuadraticModel.to_serializable` ([docs](https://docs.ocean.dwavesys.com/projects/dimod/en/stable/reference/generated/dimod.BinaryQuadraticModel.to_serializable.html#dimod.BinaryQuadraticModel.to_serializable)).

We serialize the bqm object so that we do not need to reuse code. The flow would be

```
import json

with open('filename', 'w') as fp:
    bqm = dimod.BinaryQuadraticModel.from_qubo(Q)
    json.dump(bqm.to_serializeable(), fp)

with open('filename', 'r') as fp:
    bqm = dimod.BinaryQuadraticModel.from_serializable(json.load(fp))
   Q, off = bqm.to_qubo()
```

For large QUBOs like you're describing, they are probably better off using `.from_serializable(use_bytes=True)` and `bson` encoding or similar.

**Comment by spreinhardt** [comment]
I'm not understanding.  I'm a DNX user, so I only think about graphs.  I don't ever see the QUBO that's created inside the DNX kernel, because it's sent to a solver and the results are handled inside DNX.  How do I put your suggested code inside the DNX kernel?

**Comment by arcondello** [comment]
networkx, and by extension dwave-networkx is not really designed for this use case. However, we know that advanced users might have other needs, to that end we provide the qubo generating functions for most of the graph algorithms. For instance
```
indep_nodes = dnx.maximum_independent_set(G, sampler)
```
can be done equivalently with
```
Q = dnx.maximum_weighted_independent_set_qubo(G)
response = sampler.sample_qubo(Q)

sample = next(iter(response))
indep_nodes = [node for node in sample if sample[node] > 0]
```
Therefore, to your question, they can do the above in two steps, saving in between with
```
Q = dnx.maximum_weighted_independent_set_qubo(G)
with open('filename', 'w') as fp:
    bqm = dimod.BinaryQuadraticModel.from_qubo(Q)
    json.dump(bqm.to_serializeable(), fp)
```

```
with open('filename', 'r') as fp:
    bqm = dimod.BinaryQuadraticModel.from_serializable(json.load(fp))
   Q, off = bqm.to_qubo()
response = sampler.sample_qubo(Q)

sample = next(iter(response))
indep_nodes = [node for node in sample if sample[node] > 0]
```
While this is obviously more complicated than having a bespoke API, I consider any user who knows enough to know they want to save the QUBO in a file, to be qualified to understand serialzing BQMs.

It is also worth noting the networkx has its own serialization. So assuming the user has a weighted graph and are ok with saving that rather than the QUBO itself, they can use any of the methods available [here](https://networkx.github.io/documentation/stable/reference/readwrite/index.html) to save `G`. Then simply use `indep_nodes = dnx.maximum_independent_set(G, sampler)`

**Comment by arcondello** [comment]
Probably this one: https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.json_graph.adjacency_data.html#networkx.readwrite.json_graph.adjacency_data

**Comment by spreinhardt** [comment]
Re: "I consider any user who knows enough to know they want to save the QUBO in a file ..." : 
- Using NX's graph-serialization method is reasonable for many users. 
- Your example of using BQM above again forces the user to grok lower-level Ocean details to do something common.  Plenty of our users will want to solve problems without doing so.

**Comment by arcondello** [comment]
If nx's serialization is sufficient then I believe we can consider this closed.
